Vagrant.configure("2") do |config|

  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/bionic64"
    web01.vm.network "private_network", ip: "192.168.40.11"
  end

  config.vm.define "db01" do |db01|
    db01.vm.box = "geerlingguy/centos7"
    db01.vm.network "private_network", ip: "192.168.40.12"
  end
end
