- name: Provisioning Server
  hosts: all
  become: yes
  tasks:
         - name: Install NTP on Centos
           yum:
                   name: "{{item}}"
                   state: present
           when: ansible_distribution == "CentOS"
           loop:
                   - ntp
                   - wget
                   - git
                   - zip
                   - unzip

         - name: Update apt cache
           apt:
                   update_cache: yes
                   cache_valid_time: 600
           when: ansible_os_family == 'Debian'

         - name: Install NTP on Ubuntu
           apt:
                   name: "{{item}}"
                   state: present
           when: ansible_distribution == "Ubuntu"
           loop:
                   - ntp
                   - wget
                   - git
                   - zip
                   - unzip

         - name: Start & enable NTP on Redhat
           service:
                   name: ntpd
                   state: started
                   enabled: yes
           when: ansible_os_family == "RedHat"

         - name: Add group
           group:
                   name: devops
                   state: present
         - name: Add users
           user:
                   name: "{{item}}"
                   state: present
                   groups: devops
           loop: "{{usernames}}"
