- name: Provisioning Server
  hosts: all
  become: yes
  tasks:
         - name: Install NTP on Centos
           yum:
                   name: ntp
                   state: present
           when: ansible_distribution == "CentOS"

         - name: Update apt cache
           apt:
                   update_cache: yes
                   cache_valid_time: 600
           when: ansible_os_family == 'Debian'

         - name: Install NTP on Ubuntu
           apt:
                   name: ntp
                   state: present
           when: ansible_distribution == "Ubuntu"
